name: Send iTalkBB API Request

on:
  schedule:
    # 每天 UTC 时间 00:00 运行
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  send_request:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Send GET Request with Authorization Header
      run: |
        # 使用 curl 发送 GET 请求
        # 注意：Bearer token 应该作为 GitHub Secrets 存储，而不是直接写在这里
        API_URL="https://api.italkbbtv.com/playauth/v1/live?series_id=62cbb01d4725b530583c1759&hl=zh_CN"
        AUTH_TOKEN="${{ secrets.ITALKBB_AUTH_TOKEN }}" # 从 GitHub Secrets 获取 token

        curl -X GET \
             -H "Authorization: Bearer $AUTH_TOKEN" \
             "$API_URL" \
             -o response.json # 将响应保存到文件

    - name: Display Response (Optional)
      run: |
        cat response.json
        # 你可以在这里添加更多逻辑来处理响应，例如解析 JSON，检查状态等
