name: Send iTalkBB API Request and Save Response

on:
  schedule:
    # 每天 UTC 时间 00:00 运行
    # 请注意：cron 表达式基于 UTC 时间。例如，如果你希望在北京时间上午8点运行 (GMT+8)，
    # 那么需要设置为 UTC 00:00。
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  send_request_and_save:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 确保使用最新版本的 actions/checkout

    - name: Send GET Request with Authorization Header
      run: |
        API_URL="https://api.italkbbtv.com/playauth/v1/live?series_id=62cbb01d4725b530583c1759&hl=zh_CN"
        AUTH_TOKEN="${{ secrets.ITALKBB_AUTH_TOKEN }}"

        curl -X GET \
             -H "Authorization: Bearer $AUTH_TOKEN" \
             "$API_URL" \
             -o response.json # 将响应保存到文件

    - name: Configure Git # <<< 确保有这个步骤
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and Push Response # <<< 确保有这个步骤
      run: |
        git add response.json
        # 检查是否有实际的更改，避免空提交
        git diff-index --quiet HEAD || git commit -m "Update API response.json"
        git push

    - name: Display Response (Optional)
      run: |
        cat response.json
