name: Send iTalkBB API Request and Save Response

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 00:00 运行
  workflow_dispatch: # 允许手动触发

jobs:
  send_request_and_save:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 确保使用最新版本的 actions/checkout

    - name: Send GET Request with Authorization Header
      run: |
        API_URL="https://api.italkbbtv.com/playauth/v1/live?series_id=62cbb01d4725b530583c1759&hl=zh_CN"
        AUTH_TOKEN="${{ secrets.ITALKBB_AUTH_TOKEN }}"

        curl -X GET \
             -H "Authorization: Bearer $AUTH_TOKEN" \
             "$API_URL" \
             -o response.json # 将响应保存到文件

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]" # 使用 GitHub Actions 官方 bot 用户名
        git config user.email "github-actions[bot]@users.noreply.github.com" # 使用 GitHub Actions 官方 bot 邮箱

    - name: Commit and Push Response
      run: |
        git add response.json # 添加 response.json 到 Git 暂存区
        # 检查是否有实际的更改，避免空提交
        git diff-index --quiet HEAD || git commit -m "Update API response.json"
        git push # 推送更改到远程仓库

    - name: Display Response (Optional)
      run: |
        cat response.json
